ALTER TABLE contains
    ADD FOREIGN KEY (playlist)                REFERENCES playlist(name)                ON UPDATE CASCADE ON DELETE CASCADE,
    ADD FOREIGN KEY (cd_number, track_number) REFERENCES song(cd_number, track_number) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE dj
    ADD FOREIGN KEY (id) REFERENCES employee(id) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE event
    ADD FOREIGN KEY (client)        REFERENCES client(client_number) ON UPDATE CASCADE ON DELETE RESTRICT,
    ADD FOREIGN KEY (manager)       REFERENCES manager(id)           ON UPDATE CASCADE ON DELETE SET NULL,
    ADD FOREIGN KEY (event_planner) REFERENCES eventplanner(id)      ON UPDATE CASCADE ON DELETE SET NULL,
    ADD FOREIGN KEY (dj)            REFERENCES dj(id)                ON UPDATE CASCADE ON DELETE SET NULL,
    ADD FOREIGN KEY (theme)         REFERENCES theme(name)           ON UPDATE CASCADE ON DELETE RESTRICT,
    ADD FOREIGN KEY (location)      REFERENCES location(id)          ON UPDATE CASCADE ON DELETE SET NULL,
    ADD FOREIGN KEY (playlist)      REFERENCES playlist(name)        ON UPDATE CASCADE ON DELETE SET NULL;

ALTER TABLE eventplanner
    ADD FOREIGN KEY (id) REFERENCES employee(id) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE manager
    ADD FOREIGN KEY (id) REFERENCES employee(id) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE request
    ADD FOREIGN KEY (event_id) REFERENCES event(id) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE song
    ADD FOREIGN KEY (cd_number) REFERENCES cd(cd_number) ON UPDATE CASCADE ON DELETE CASCADE,
    ADD FOREIGN KEY (genre)     REFERENCES genre(name)   ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE specialization
    ADD FOREIGN KEY (dj)    REFERENCES dj(id)      ON UPDATE CASCADE ON DELETE CASCADE,
    ADD FOREIGN KEY (genre) REFERENCES genre(name) ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE specializes
    ADD FOREIGN KEY (subgenre) REFERENCES genre(name) ON UPDATE CASCADE ON DELETE CASCADE,
    ADD FOREIGN KEY (genre)    REFERENCES genre(name) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE suitablefor
    ADD FOREIGN KEY (theme)    REFERENCES theme(name)    ON UPDATE CASCADE ON DELETE CASCADE,
    ADD FOREIGN KEY (playlist) REFERENCES playlist(name) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE supervision
    ADD FOREIGN KEY (employee_id)   REFERENCES employee(id) ON UPDATE CASCADE ON DELETE CASCADE,
    ADD FOREIGN KEY (supervisor_id) REFERENCES manager(id)  ON UPDATE CASCADE ON DELETE CASCADE;
