# version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    command: --log-bin-trust-function-creators=1 --local-infile=1 --secure-file-priv=
    environment:
      MYSQL_USER: ${DB_USER:-user}
      MYSQL_PASSWORD: ${DB_PASSWORD:-password}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-root}
      MYSQL_DATABASE: ${DB_DATABASE:-database}
    volumes:
      - db_data:/var/lib/mysql
      - ./schema:/docker-entrypoint-initdb.d:ro
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8080:80"
    depends_on:
      - db

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    restart: always
    ports:
      - "80:5000"
    volumes:
      - ./src:/usr/src/app
    depends_on:
      - db
    environment:
      MYSQL_HOST: db
      MYSQL_USER: ${DB_USER:-user}
      MYSQL_PASSWORD: ${DB_PASSWORD:-password}
      MYSQL_DATABASE: ${DB_DATABASE:-database}

volumes:
  db_data:
